### ISSUE TITLE
Coroutines support

### ISSUE THREAD

**Issue by ValentiWorkLearning** [tobanteEmbedded/tetl#4]
Thank you for the such library. Do you have any plans for supporting the C++20 coroutines?
Probably, you can use a kind of cppcoro fork with the embedded systems specific optimizations.
I guess, that their concept of scheduling coroutine in a specific execution context ( schedule_on method) can be used with a RTOS wrapper for combining the facilities if a RTOS with the executors concept.

For instance, an embedded application can include a network thread, a kind of UI thread and peripheral thread for some sensors interaction. Just imagine a case when an embedded developer will be given for an opportunity for writing a code like a:

```cpp
cppcoro::task<> typical_embedded_procedure()
{
auto sensor_value = co_await schedule_on(peripheral_executor, read_data_from_a_sensor); //will use DMA access internally
co_await schedule_on(network_executor, send_value_to_ble_peripheral(sensor_value));
co_yield ui_executor;
auto ui_widget = get_gfx_control();
ui_widget->set_control_value(sensor_value);
}

```
I have a prototype which based on a such idea. I've used the coroutines internally for the seamless integration with the Nordic SPI DMA.
It's available there:

https://wandbox.org/permlink/y6s7UVqLQUBy67xK
If you want, I'll advise you to take a glance at the article:
https://habr.com/ru/post/566070/
It was written in Russian, but the code examples had been supplied with comments. 

Thank you again. If necessary, I'll open for the discussion about the further ideas of the library!

**Comment by tobiashienzsch** [comment]
Years later...

Sorry for not replying. Never had time to thing about it. I will close this for now. If you see this reach out, let's talk about it. :)
